# Generated by Django 4.1.4 on 2023-01-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('volume', models.IntegerField(default=0)),
                ('market_capital', models.FloatField(default=0)),
                ('credit_rating', models.FloatField(default=0)),
            ],
        ),
    ]
