# Generated by Django 4.1.4 on 2023-01-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_product_id_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ser_no',
            field=models.IntegerField(null=True),
        ),
    ]
